name: Deploy to Production

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST '\
          if [ ! -d "~/hngx-stage2-fastapi-book-project-cicd" ]; then \
            git clone https://github.com/lankiman/hngx-stage2-fastapi-book-project-cicd.git && \
            cd hngx-stage2-fastapi-book-project-cicd && \
            python3 -m venv venv && \
            source venv/bin/activate && \
            pip install -r requirements.txt; \
          else \
            cd ~/hngx-stage2-fastapi-book-project-cicd && \
            git pull origin main; \
          fi && \
          pkill -f "uvicorn main:app" || true && \
          source venv/bin/activate && \
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &'
