name: Deploy to Production

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Write the private key to a file
          echo "$SSH_PRIVATE_KEY" > id_rsa
          chmod 600 id_rsa

          # Connect to the server and deploy
          ssh -i id_rsa -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa $SSH_USER@$SSH_HOST << 'EOF'
            set -e

            # Clone repo if not exists, else pull latest changes
            if [ ! -d "$HOME/hngx-stage2-fastapi-book-project-cicd" ]; then
              git clone https://github.com/lankiman/hngx-stage2-fastapi-book-project-cicd.git
            fi
            
            cd hngx-stage2-fastapi-book-project-cicd

            # Update repo
            git pull origin main

            # Ensure Python and dependencies are installed
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt

            # Restart the FastAPI application
            pkill -f "uvicorn main:app" || true
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &
          EOF

          # Clean up the private key file
          rm -f id_rsa
